controller_list:
  - name: fake_edmo_control_controller
    type: $(arg fake_execution_type)
    joints:
      - Rev1
      - Rev8
      - Rev13
initial:  # Define initial robot poses per group
  - group: edmo_control
    pose: home