edmo_control_controller:
  type: effort_controllers/JointTrajectoryController
  joints:
    - Rev1
    - Rev8
    - Rev13
  gains:
    Rev1:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    Rev8:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    Rev13:
      p: 100
      d: 1
      i: 1
      i_clamp: 1