<?xml version="1.0" ?>
<robot name="edmo_snake" xmlns:xacro="http://www.ros.org/wiki/xacro">

<xacro:include filename="$(find edmo_snake_description)/urdf/materials.xacro" />
<xacro:include filename="$(find edmo_snake_description)/urdf/edmo_snake.trans" />
<xacro:include filename="$(find edmo_snake_description)/urdf/edmo_snake.gazebo" />

<xacro:property name="base_x_offset" value="0.0" />
<xacro:property name="base_y_offset" value="0.015" />
<xacro:property name="base_z_offset" value="0.02" />

<xacro:property name="arm_x_offset" value="0.027" />
<xacro:property name="arm_z_offset" value="0.02" />
<xacro:property name="cover_x_offset" value="0.02" />
<xacro:property name="cover_z_offset" value="0.02" />
<xacro:property name="straight_connector_x_offset" value="0.06" />
<xacro:property name="second_arm_x_offset" value="0.106" />

<xacro:property name="motor_x_offset" value="0.018" />
<xacro:property name="motor_y_offset" value="0.002" />
<xacro:property name="motor_z_offset" value="0.0008" />

<xacro:property name="arm_x_intertia_offset" value="0.03" />

<link name="dummy">
</link>

<link name="base_link">
  <inertial>
    <origin xyz="0.0 0.0 0.0" rpy="0 0 0"/>
    <mass value="0.040787"/>
    <inertia ixx="0.000021171851916666665" ixy="0" ixz="0" iyy="0.000028667280707362297" iyz="0" izz="0.00004372108262402896" />
  </inertial>
  <visual>
    <origin xyz="-${base_x_offset} -${base_y_offset} -${base_z_offset}" rpy="0 0 0"/>
    <geometry>
      <mesh filename="package://edmo_snake_description/meshes/base_link.stl" scale="0.001 0.001 0.001"/>
    </geometry>
    <material name="silver"/>
  </visual>
  <collision>
    <origin xyz="${base_x_offset} -${base_y_offset} -${base_z_offset}" rpy="0 0 0"/>
    <geometry>
      <mesh filename="package://edmo_snake_description/meshes/base_link.stl" scale="0.001 0.001 0.001"/>
    </geometry>
  </collision>
</link>

<link name="arm_1_1">
  <inertial>
    <origin xyz="${arm_x_intertia_offset} 0.0 0.0" rpy="0 0 0"/>
    <mass value="0.039526"/>
    <inertia ixx="0.000022493587833333332" ixy="0" ixz="0" iyy="0.00003206876133333333" iyz="0" izz="0.00004863344916666667" />
  </inertial>
  <visual>
    <origin xyz="-${arm_x_offset} -${base_y_offset} -${arm_z_offset}" rpy="0 0 0"/>
    <geometry>
      <mesh filename="package://edmo_snake_description/meshes/arm_1_1.stl" scale="0.001 0.001 0.001"/>
    </geometry>
    <material name="silver"/>
  </visual>
  <collision>
    <origin xyz="-${arm_x_offset} -${base_y_offset} -${arm_z_offset}" rpy="0 0 0"/>
    <geometry>
      <mesh filename="package://edmo_snake_description/meshes/arm_1_1.stl" scale="0.001 0.001 0.001"/>
    </geometry>
  </collision>
</link>

<link name="cover_1_1">
  <inertial>
    <origin xyz="0.0 0.0 0.0" rpy="0 0 0"/>
    <mass value="0.015429"/>
    <inertia ixx="0.0000028929375" ixy="0" ixz="0" iyy="0.00000491799375" iyz="0" izz="0.00000723234375" />
  </inertial>
  <visual>
    <origin xyz="-${cover_x_offset} -${base_y_offset} -${cover_z_offset}" rpy="0 0 0"/>
    <geometry>
      <mesh filename="package://edmo_snake_description/meshes/cover_1_1.stl" scale="0.001 0.001 0.001"/>
    </geometry>
    <material name="silver"/>
  </visual>
  <collision>
    <origin xyz="-${cover_x_offset} -${base_y_offset} -${cover_z_offset}" rpy="0 0 0"/>
    <geometry>
      <mesh filename="package://edmo_snake_description/meshes/cover_1_1.stl" scale="0.001 0.001 0.001"/>
    </geometry>
  </collision>
</link>

<link name="straight_connector_1_1">
  <inertial>
    <origin xyz="0.0 0.0 0.0" rpy="0 0 0"/>
    <mass value="0.007565"/>
    <inertia ixx="0.000002074973939693871" ixy="0" ixz="0" iyy="0.0000008986162756831851" iyz="0" izz="0.0000015031782103951184" />
  </inertial>
  <visual>
    <origin xyz="-${straight_connector_x_offset+arm_x_offset} -${base_y_offset} -${base_z_offset}" rpy="0 0 0"/>
    <geometry>
      <mesh filename="package://edmo_snake_description/meshes/straight_connector_1_1.stl" scale="0.001 0.001 0.001"/>
    </geometry>
    <material name="silver"/>
  </visual>
  <collision>
    <origin xyz="-${straight_connector_x_offset+arm_x_offset} -${base_y_offset} -${base_z_offset}" rpy="0 0 0"/>
    <geometry>
      <mesh filename="package://edmo_snake_description/meshes/straight_connector_1_1.stl" scale="0.001 0.001 0.001"/>
    </geometry>
  </collision>
</link>

<link name="clip_connector_1_1">
  <inertial>
    <origin xyz="0.0 0.0 0.0" rpy="0 0 0"/>
    <mass value="0.004143"/>
    <inertia  ixx="0.0000008225581966461201" ixy="0" ixz="0" iyy="0.00000014973490050335027" iyz="0" izz="0.0000009247245608945109" />
  </inertial>
  <visual>
    <origin xyz="-${straight_connector_x_offset+arm_x_offset} -${base_y_offset} -${base_z_offset}" rpy="0 0 0"/>
    <geometry>
      <mesh filename="package://edmo_snake_description/meshes/clip_connector_1_1.stl" scale="0.001 0.001 0.001"/>
    </geometry>
    <material name="silver"/>
  </visual>
  <collision>
    <origin xyz="-${straight_connector_x_offset+arm_x_offset} -${base_y_offset} -${base_z_offset}" rpy="0 0 0"/>
    <geometry>
      <mesh filename="package://edmo_snake_description/meshes/clip_connector_1_1.stl" scale="0.001 0.001 0.001"/>
    </geometry>
  </collision>
</link>

<link name="base_2_1">
  <inertial>
    <origin xyz="0.0 0.0 0.0" rpy="0 0 0"/>
    <mass value="0.040787"/>
    <inertia ixx="0.000021171851916666665" ixy="0" ixz="0" iyy="0.000028667280707362297" iyz="0" izz="0.00004372108262402896" />
  </inertial>
  <visual>
    <origin xyz="0.0 -${base_y_offset} -${base_z_offset}" rpy="0 0 0"/>
    <geometry>
      <mesh filename="package://edmo_snake_description/meshes/base_link.stl" scale="0.001 0.001 0.001"/>
    </geometry>
    <material name="silver"/>
  </visual>
  <collision>
    <origin xyz="0.0 -${base_y_offset} -${base_z_offset}" rpy="0 0 0"/>
    <geometry>
      <mesh filename="package://edmo_snake_description/meshes/base_link.stl" scale="0.001 0.001 0.001"/>
    </geometry>
  </collision>
</link>

<link name="cover_2_1">
  <inertial>
    <origin xyz="0.0 0.0 0.0" rpy="0 0 0"/>
    <mass value="0.015429"/>
    <inertia ixx="0.0000028929375" ixy="0" ixz="0" iyy="0.00000491799375" iyz="0" izz="0.00000723234375" />
  </inertial>
  <visual>
    <origin xyz="-${cover_x_offset} -${base_y_offset} -${cover_z_offset}" rpy="0 0 0"/>
    <geometry>
      <mesh filename="package://edmo_snake_description/meshes/cover_1_1.stl" scale="0.001 0.001 0.001"/>
    </geometry>
    <material name="silver"/>
  </visual>
  <collision>
    <origin xyz="-${cover_x_offset} -${base_y_offset} -${cover_z_offset}" rpy="0 0 0"/>
    <geometry>
      <mesh filename="package://edmo_snake_description/meshes/cover_1_1.stl" scale="0.001 0.001 0.001"/>
    </geometry>
  </collision>
</link>

<link name="arm_2_1">
  <inertial>
    <origin xyz="${arm_x_intertia_offset} 0.0 0.0" rpy="0 0 0"/>
    <mass value="0.039526"/>
    <inertia ixx="0.000022493587833333332" ixy="0" ixz="0" iyy="0.00003206876133333333" iyz="0" izz="0.00004863344916666667" />
  </inertial>
  <visual>
    <origin xyz="-${arm_x_offset} -${base_y_offset} -${arm_z_offset}" rpy="0 0 0"/>
    <geometry>
      <mesh filename="package://edmo_snake_description/meshes/arm_1_1.stl" scale="0.001 0.001 0.001"/>
    </geometry>
    <material name="silver"/>
  </visual>
  <collision>
    <origin xyz="-${arm_x_offset} -${base_y_offset} -${arm_z_offset}" rpy="0 0 0"/>
    <geometry>
      <mesh filename="package://edmo_snake_description/meshes/arm_1_1.stl" scale="0.001 0.001 0.001"/>
    </geometry>
  </collision>
</link>

<link name="straight_connector_2_1">
  <inertial>
    <origin xyz="0.0 0.0 0.0" rpy="0 0 0"/>
    <mass value="0.007565"/>
    <inertia ixx="0.000002074973939693871" ixy="0" ixz="0" iyy="0.0000008986162756831851" iyz="0" izz="0.0000015031782103951184" />
  </inertial>
  <visual>
    <origin xyz="-${straight_connector_x_offset+arm_x_offset} -${base_y_offset} -${base_z_offset}" rpy="0 0 0"/>
    <geometry>
      <mesh filename="package://edmo_snake_description/meshes/straight_connector_1_1.stl" scale="0.001 0.001 0.001"/>
    </geometry>
    <material name="silver"/>
  </visual>
  <collision>
    <origin xyz="-${straight_connector_x_offset+arm_x_offset} -${base_y_offset} -${base_z_offset}" rpy="0 0 0"/>
    <geometry>
      <mesh filename="package://edmo_snake_description/meshes/straight_connector_1_1.stl" scale="0.001 0.001 0.001"/>
    </geometry>
  </collision>
</link>

<link name="clip_connector_2_1">
  <inertial>
    <origin xyz="0.0 0.0 0.0" rpy="0 0 0"/>
    <mass value="0.004143"/>
    <inertia  ixx="0.0000008225581966461201" ixy="0" ixz="0" iyy="0.00000014973490050335027" iyz="0" izz="0.0000009247245608945109" />
  </inertial>
  <visual>
    <origin xyz="-${straight_connector_x_offset+arm_x_offset} -${base_y_offset} -${base_z_offset}" rpy="0 0 0"/>
    <geometry>
      <mesh filename="package://edmo_snake_description/meshes/clip_connector_1_1.stl" scale="0.001 0.001 0.001"/>
    </geometry>
    <material name="silver"/>
  </visual>
  <collision>
    <origin xyz="-${straight_connector_x_offset+arm_x_offset} -${base_y_offset} -${base_z_offset}" rpy="0 0 0"/>
    <geometry>
      <mesh filename="package://edmo_snake_description/meshes/clip_connector_1_1.stl" scale="0.001 0.001 0.001"/>
    </geometry>
  </collision>
</link>

<link name="base_3_1">
  <inertial>
    <origin xyz="0.0 0.0 0.0" rpy="0 0 0"/>
    <mass value="0.040787"/>
    <inertia ixx="0.000021171851916666665" ixy="0" ixz="0" iyy="0.000028667280707362297" iyz="0" izz="0.00004372108262402896" />
  </inertial>
  <visual>
    <origin xyz="0.0 -${base_y_offset} -${base_z_offset}" rpy="0 0 0"/>
    <geometry>
      <mesh filename="package://edmo_snake_description/meshes/base_link.stl" scale="0.001 0.001 0.001"/>
    </geometry>
    <material name="silver"/>
  </visual>
  <collision>
    <origin xyz="0.0 -${base_y_offset} -${base_z_offset}" rpy="0 0 0"/>
    <geometry>
      <mesh filename="package://edmo_snake_description/meshes/base_link.stl" scale="0.001 0.001 0.001"/>
    </geometry>
  </collision>
</link>

<link name="cover_3_1">
  <inertial>
    <origin xyz="0.0 0.0 0.0" rpy="0 0 0"/>
    <mass value="0.015429"/>
    <inertia ixx="0.0000028929375" ixy="0" ixz="0" iyy="0.00000491799375" iyz="0" izz="0.00000723234375" />
  </inertial>
  <visual>
    <origin xyz="-${cover_x_offset} -${base_y_offset} -${cover_z_offset}" rpy="0 0 0"/>
    <geometry>
      <mesh filename="package://edmo_snake_description/meshes/cover_1_1.stl" scale="0.001 0.001 0.001"/>
    </geometry>
    <material name="silver"/>
  </visual>
  <collision>
    <origin xyz="-${cover_x_offset} -${base_y_offset} -${cover_z_offset}" rpy="0 0 0"/>
    <geometry>
      <mesh filename="package://edmo_snake_description/meshes/cover_1_1.stl" scale="0.001 0.001 0.001"/>
    </geometry>
  </collision>
</link>

<link name="arm_3_1">
  <inertial>
    <origin xyz="${arm_x_intertia_offset} 0.0 0.0" rpy="0 0 0"/>
    <mass value="0.039526"/>
    <inertia ixx="0.000022493587833333332" ixy="0" ixz="0" iyy="0.00003206876133333333" iyz="0" izz="0.00004863344916666667" />
  </inertial>
  <visual>
    <origin xyz="-${arm_x_offset} -${base_y_offset} -${arm_z_offset}" rpy="0 0 0"/>
    <geometry>
      <mesh filename="package://edmo_snake_description/meshes/arm_1_1.stl" scale="0.001 0.001 0.001"/>
    </geometry>
    <material name="silver"/>
  </visual>
  <collision>
    <origin xyz="-${arm_x_offset} -${base_y_offset} -${arm_z_offset}" rpy="0 0 0"/>
    <geometry>
      <mesh filename="package://edmo_snake_description/meshes/arm_1_1.stl" scale="0.001 0.001 0.001"/>
    </geometry>
  </collision>
</link>

<link name="motor_box_1">
  <inertial>
    <origin xyz="0.0 0.0 0.0" rpy="0 0 0"/>
    <mass value="0.057"/>
    <inertia ixx="0.0000090309375" ixy="0" ixz="0" iyy="0.000008846874999999999" iyz="0" izz="0.000014265437499999999" />
  </inertial>
  <visual>
    <origin xyz="0.003 -0.058 -0.01" rpy="0 0 0"/>
    <geometry>
      <mesh filename="package://edmo_snake_description/meshes/motor_box_1.stl" scale="0.001 0.001 0.001"/>
    </geometry>
    <material name="silver"/>
  </visual>
  <collision>
    <origin xyz="0.003 -0.058 -0.01" rpy="0 0 0"/>
    <geometry>
      <mesh filename="package://edmo_snake_description/meshes/motor_box_1.stl" scale="0.001 0.001 0.001"/>
    </geometry>
  </collision>
</link>

<link name="motor_box_2">
  <inertial>
    <origin xyz="0.0 0.0 0.0" rpy="0 0 0"/>
    <mass value="0.057"/>
    <inertia ixx="0.0000090309375" ixy="0" ixz="0" iyy="0.000008846874999999999" iyz="0" izz="0.000014265437499999999" />
  </inertial>
  <visual>
    <origin xyz="0.003 -0.058 -0.01" rpy="0 0 0"/>
    <geometry>
      <mesh filename="package://edmo_snake_description/meshes/motor_box_1.stl" scale="0.001 0.001 0.001"/>
    </geometry>
    <material name="silver"/>
  </visual>
  <collision>
    <origin xyz="0.003 -0.058 -0.01" rpy="0 0 0"/>
    <geometry>
      <mesh filename="package://edmo_snake_description/meshes/motor_box_1.stl" scale="0.001 0.001 0.001"/>
    </geometry>
  </collision>
</link>

<link name="motor_box_3">
  <inertial>
    <origin xyz="0.0 0.0 0.0" rpy="0 0 0"/>
    <mass value="0.057"/>
    <inertia ixx="0.0000090309375" ixy="0" ixz="0" iyy="0.000008846874999999999" iyz="0" izz="0.000014265437499999999" />
  </inertial>
  <visual>
    <origin xyz="0.003 -0.058 -0.01" rpy="0 0 0"/>
    <geometry>
      <mesh filename="package://edmo_snake_description/meshes/motor_box_1.stl" scale="0.001 0.001 0.001"/>
    </geometry>
    <material name="silver"/>
  </visual>
  <collision>
    <origin xyz="0.003 -0.058 -0.01" rpy="0 0 0"/>
    <geometry>
      <mesh filename="package://edmo_snake_description/meshes/motor_box_1.stl" scale="0.001 0.001 0.001"/>
    </geometry>
  </collision>
</link>

<joint name="Rigid0" type="fixed">
  <origin xyz="0.0 0.0 0.0" rpy="0 0 0"/>
  <parent link="dummy"/>
  <child link="base_link"/>
</joint>

<joint name="Rev1" type="revolute">
  <origin xyz="${arm_x_offset} 0.0 0.0" rpy="0 0 0"/>
  <parent link="base_link"/>
  <child link="arm_1_1"/>
  <axis xyz="0.0 1.0 0.0"/>
  <!-- Joint limits -->
  <limit lower="-2.00"
        upper="2.00"
        effort="1.0"
        velocity="0.5"/>
</joint>

<joint name="Rigid2" type="fixed">
  <origin xyz="${cover_x_offset} 0.0 0.0" rpy="0 0 0"/>
  <parent link="base_link"/>
  <child link="cover_1_1"/>
</joint>

<joint name="Rigid3" type="fixed">
  <origin xyz="${straight_connector_x_offset} 0.0 0.0" rpy="0 0 0"/>
  <parent link="arm_1_1"/>
  <child link="straight_connector_1_1"/>
</joint>

<joint name="Rigid4" type="fixed">
  <origin xyz="${straight_connector_x_offset} 0.0 0.0" rpy="0 0 0"/>
  <parent link="arm_1_1"/>
  <child link="clip_connector_1_1"/>
</joint>

<joint name="Rigid5" type="fixed">
  <origin xyz="${second_arm_x_offset} 0.0 0.0" rpy="0 0 0"/>
  <parent link="arm_1_1"/>
  <child link="base_2_1"/>
</joint>

<joint name="Rigid7" type="fixed">
  <origin xyz="${cover_x_offset} 0.0 0.0" rpy="0 0 0"/>
  <parent link="base_2_1"/>
  <child link="cover_2_1"/>
</joint>

<joint name="Rev8" type="revolute">
  <origin xyz="${arm_x_offset} 0.0 0.0" rpy="0 0 0"/>
  <parent link="base_2_1"/>
  <child link="arm_2_1"/>
  <axis xyz="0.0 1.0 0.0"/>
  <!-- Joint limits -->
  <limit lower="-2.00"
        upper="2.00"
        effort="1.0"
        velocity="0.5"/>
</joint>

<joint name="Rigid9" type="fixed">
  <origin xyz="${straight_connector_x_offset} 0.0 0.0" rpy="0 0 0"/>
  <parent link="arm_2_1"/>
  <child link="straight_connector_2_1"/>
</joint>

<joint name="Rigid10" type="fixed">
  <origin xyz="${second_arm_x_offset} 0.0 0.0" rpy="0 0 0"/>
  <parent link="arm_2_1"/>
  <child link="base_3_1"/>
</joint>

<joint name="Rigid11" type="fixed">
  <origin xyz="${straight_connector_x_offset} 0.0 0.0" rpy="0 0 0"/>
  <parent link="arm_2_1"/>
  <child link="clip_connector_2_1"/>
</joint>

<joint name="Rigid12" type="fixed">
  <origin xyz="${cover_x_offset} 0.0 0.0" rpy="0 0 0"/>
  <parent link="base_3_1"/>
  <child link="cover_3_1"/>
</joint>

<joint name="Rev13" type="revolute">
  <origin xyz="${arm_x_offset} 0.0 0.0" rpy="0 0 0"/>
  <parent link="base_3_1"/>
  <child link="arm_3_1"/>
  <axis xyz="0.0 1.0 0.0"/>
  <!-- Joint limits -->
  <limit lower="-2.00"
        upper="2.00"
        effort="1.0"
        velocity="0.5"/>
</joint>

<joint name="Rigid14" type="fixed">
  <origin xyz="${motor_x_offset} ${motor_y_offset} ${motor_z_offset}" rpy="0 0 0"/>
  <parent link="base_link"/>
  <child link="motor_box_1"/>
</joint>

<joint name="Rigid15" type="fixed">
  <origin xyz="${motor_x_offset} ${motor_y_offset} ${motor_z_offset}" rpy="0 0 0"/>
  <parent link="base_2_1"/>
  <child link="motor_box_2"/>
</joint>

<joint name="Rigid16" type="fixed">
  <origin xyz="${motor_x_offset} ${motor_y_offset} ${motor_z_offset}" rpy="0 0 0"/>
  <parent link="base_3_1"/>
  <child link="motor_box_3"/>
</joint>

</robot>
