joint_limits:
  Rev1:
    has_position_limits: true
    min_position: -1.57
    max_position: 1.57
    has_velocity_limits: false
    max_velocity: 0.0
    has_acceleration_limits: false
    max_acceleration: 0.0
    has_jerk_limits: false
    max_jerk: 0
    has_effort_limits: true
    max_effort: 255

  Rev8:
    has_position_limits: true
    min_position: -1.57
    max_position: 1.57
    has_velocity_limits: false
    max_velocity: 0.0
    has_acceleration_limits: false
    max_acceleration: 0.0
    has_jerk_limits: false
    max_jerk: 0
    has_effort_limits: true
    max_effort: 255

  Rev13:
    has_position_limits: true
    min_position: -1.57
    max_position: 1.57
    has_velocity_limits: false
    max_velocity: 0.0
    has_acceleration_limits: false
    max_acceleration: 0.0
    has_jerk_limits: false
    max_jerk: 0
    has_effort_limits: true
    max_effort: 255
